"""withdrawal confirmation

Revision ID: 18dfbeea62f3
Revises: d6d99025a62f
Create Date: 2022-06-30 05:23:22.615949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dfbeea62f3'
down_revision = 'd6d99025a62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_confirmation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('crypto_withdrawal_id', sa.Integer(), nullable=True),
    sa.Column('fiat_withdrawal_id', sa.Integer(), nullable=True),
    sa.Column('address_book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_book_id'], ['address_book.id'], ),
    sa.ForeignKeyConstraint(['crypto_withdrawal_id'], ['crypto_withdrawal.id'], ),
    sa.ForeignKeyConstraint(['fiat_withdrawal_id'], ['fiat_withdrawal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret'),
    sa.UniqueConstraint('token')
    )
    op.create_foreign_key('fk_crown_payment_fiat_deposit', 'fiat_deposit', 'crown_payment', ['crown_payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_crown_payment_fiat_deposit', 'fiat_deposit', type_='foreignkey')
    op.drop_table('withdrawal_confirmation')
    # ### end Alembic commands ###
