"""add_crypto_addr_check_interval

Revision ID: 7a42665e91fc
Revises: 38ca40af34a1
Create Date: 2023-02-01 04:01:20.992737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a42665e91fc'
down_revision = '38ca40af34a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_address', sa.Column('check_interval', sa.BigInteger(), nullable=True))
    op.execute('UPDATE crypto_address SET check_interval = 300')
    op.alter_column('crypto_address', 'check_interval', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_address', 'check_interval')
    # ### end Alembic commands ###
