"""remit table payment method info

Revision ID: ba6c54c79e5d
Revises: 029ae574b8c7
Create Date: 2023-02-10 09:19:42.396306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6c54c79e5d'
down_revision = '029ae574b8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_method_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_method_name', sa.String(), nullable=True))
    op.execute("UPDATE remit SET payment_method_category = ''")
    op.execute("UPDATE remit SET payment_method_code = ''")
    op.execute("UPDATE remit SET payment_method_name = ''")
    with op.batch_alter_table('remit', schema=None) as batch_op:
        batch_op.alter_column('payment_method_category', nullable=False)
        batch_op.alter_column('payment_method_code', nullable=False)
        batch_op.alter_column('payment_method_name', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remit', schema=None) as batch_op:
        batch_op.drop_column('payment_method_name')
        batch_op.drop_column('payment_method_code')
        batch_op.drop_column('payment_method_category')

    # ### end Alembic commands ###
