"""remit_confirmation

Revision ID: cd44e91b8478
Revises: ba6c54c79e5d
Create Date: 2023-02-28 23:58:26.327872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd44e91b8478'
down_revision = 'ba6c54c79e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remit_confirmation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('remit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['remit_id'], ['remit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('remit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('bolt11', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recipient_amount', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('recipient_asset', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'broker_order', ['order_id'], ['id'])
    op.execute("UPDATE remit SET amount = 0")
    op.execute("UPDATE remit SET bolt11 = ''")
    op.execute("UPDATE remit SET recipient_amount = 0")
    op.execute("UPDATE remit SET recipient_asset = ''")
    with op.batch_alter_table('remit', schema=None) as batch_op:
        batch_op.alter_column('amount', nullable=False)
        batch_op.alter_column('bolt11', nullable=False)
        batch_op.alter_column('recipient_amount', nullable=False)
        batch_op.alter_column('recipient_asset', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('recipient_asset')
        batch_op.drop_column('recipient_amount')
        batch_op.drop_column('bolt11')
        batch_op.drop_column('amount')

    op.drop_table('remit_confirmation')
    # ### end Alembic commands ###
