"""payout_request_has_address_book

Revision ID: d6d99025a62f
Revises: dc60f2b41f7c
Create Date: 2022-06-03 20:33:27.085402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d99025a62f'
down_revision = 'dc60f2b41f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_book', sa.Column('account_name', sa.String(), nullable=True))
    op.add_column('address_book', sa.Column('account_addr_01', sa.String(), nullable=True))
    op.add_column('address_book', sa.Column('account_addr_02', sa.String(), nullable=True))
    op.add_column('address_book', sa.Column('account_addr_country', sa.String(), nullable=True))
    op.add_column('payout_request', sa.Column('reference', sa.String(), nullable=False))
    op.add_column('payout_request', sa.Column('code', sa.String(), nullable=False))
    op.add_column('payout_request', sa.Column('address_book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payout_request', 'address_book', ['address_book_id'], ['id'])
    op.drop_column('payout_request', 'receiver_reference')
    op.drop_column('payout_request', 'sender_code')
    op.drop_column('payout_request', 'sender')
    op.drop_column('payout_request', 'receiver_particulars')
    op.drop_column('payout_request', 'sender_reference')
    op.drop_column('payout_request', 'receiver_account')
    op.drop_column('payout_request', 'sender_account')
    op.drop_column('payout_request', 'receiver_code')
    op.drop_column('payout_request', 'receiver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payout_request', sa.Column('receiver', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payout_request', sa.Column('receiver_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payout_request', sa.Column('sender_account', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payout_request', sa.Column('receiver_account', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payout_request', sa.Column('sender_reference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payout_request', sa.Column('receiver_particulars', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payout_request', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payout_request', sa.Column('sender_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payout_request', sa.Column('receiver_reference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payout_request', type_='foreignkey')
    op.drop_column('payout_request', 'address_book_id')
    op.drop_column('payout_request', 'code')
    op.drop_column('payout_request', 'reference')
    op.drop_column('address_book', 'account_addr_country')
    op.drop_column('address_book', 'account_addr_02')
    op.drop_column('address_book', 'account_addr_01')
    op.drop_column('address_book', 'account_name')
    # ### end Alembic commands ###
