---
- name: beryllium
  hosts: all
  become: yes
  become_user: root

  tasks:

    - name: get beryllium code
      ansible.builtin.git:
        repo: 'https://github.com/zap-me/beryllium.git'
        dest: /opt/beryllium
        version: '{{ deploy_branch }}'
        force: yes

    - name: get alloy code
      ansible.builtin.git:
        repo: 'https://github.com/zap-me/alloy.git'
        dest: /opt/beryllium/web/alloy
        version: gh-pages

    - name: build containers
      shell:
        cmd: cd /opt/beryllium && ./build-docker-images.sh

    - name: run containers
      shell:
        cmd: cd /opt/beryllium && docker-compose up --detach