---
- name: docker
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: install packages (1)
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: fetch docker apt key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ansible_architecture}}] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
        state: present

    - name: install packages (2)
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: install docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 755