---
- name: sshd
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: enable RSAAuthentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#?RSAAuthentication" line="RSAAuthentication yes"

    - name: enable PubkeyAuthentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PubkeyAuthentication" line="PubkeyAuthentication yes"

    - name: disable PasswordAuthentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"

    - name: disable ChallengeResponseAuthentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#?ChallengeResponseAuthentication" line="ChallengeResponseAuthentication no"

    - name: disable UsePAM
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#?UsePAM" line="UsePAM no"

    # LogLevel VERBOSE logs user's key fingerprint on login.
    - name: set LogLevel VERBOSE
      lineinfile: dest=/etc/ssh/sshd_config regexp="^LogLevel" line="LogLevel VERBOSE"

    - name: disallow root login
      when: ssh_disallow_root
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin no"

    - name: reload sshd
      service: name=sshd state=reloaded
